# Datos del proyecto en SonarQube
sonar.projectKey=FintechHomeKids
sonar.projectName=FintechHomeKids

# Dirección del servidor Docker local cambiado al puerto correcto
sonar.host.url=http://localhost:9001
sonar.token=sqp_37836f5a17664a364b1fedf52c4d2c2a9ae0bcf2

# Configuración de escaneo para Swift
sonar.sources=.
sonar.sourceEncoding=UTF-8

# Exclusión de archivos binarios, dependencias y carpetas de compilación
sonar.exclusions=**/*.xcodeproj/**,**/*.xcworkspace/**,Pods/**,DerivedData/**,**/*Tests/**

# Ruta del reporte de calidad que generará SwiftLint
sonar.swift.swiftlint.reportPaths=swiftlint-report.json
