fastlane_version "2.0.0"

default_platform(:ios)

platform :ios do

  # Nueva lane de tests
  desc 'Builds project and executes unit tests'
  lane :unit_test do |options|
    scan(
      clean: options[:clean] || true,
      skip_package_dependencies_resolution: options[:skip_package_dependencies_resolution] || false
    )
  end

  desc "Distribuye la build a testers via Firebase App Distribution"
  lane :distribute do |options|
    
    # 0. Ejecutar tests antes de distribuir (Opcional pero muy recomendado)
    # unit_test(clean: true) 

    current_scheme = options[:scheme] || "FintechKids-Pro" 

    increment_build_number(xcodeproj: "fintechKids.xcodeproj")
    
    gym(
      scheme: current_scheme, 
      configuration: "Release",
      export_method: "development", 
      clean: true,
      output_directory: "build",
      output_name: "#{current_scheme}.ipa" 
    )

    firebase_app_distribution(
      app: "1:454083888604:ios:39e954b6a2233c6c833b19",
      ipa_path: "build/#{current_scheme}.ipa",
      groups: "QA_Team", 
      release_notes: options[:notes] || "Build de prueba inicial para #{current_scheme}.",
    )

    commit_version_bump(
      message: "Increment build number to #{get_build_number}",
      xcodeproj: "fintechKids.xcodeproj", 
      force: true, 
      include: [
          "fintechKids.xcodeproj/project.pbxproj", 
          "fintechKids/Configuration/Info-Dev.plist", 
          "fintechKids/Configuration/Info-Pro.plist"
      ]
    )
  end
end